/**
 * Integration tests for Story 7.5: Export pipeline integration
 * 
 * Validates that specs generated by `autoqa plan` can be exported to
 * Playwright Test via Epic 4 pipeline without depending on planner-specific metadata.
 */
import { describe, it, expect } from 'vitest'
import { buildMarkdownForTestCase } from '../../src/plan/output.js'
import { parseMarkdownSpec } from '../../src/markdown/parse-markdown-spec.js'
import type { TestCasePlan } from '../../src/plan/types.js'

describe('Plan Export Integration (Epic 4)', () => {
  describe('AC3: Export pipeline compatibility', () => {
    it('should generate specs that rely only on standard IR/locator/assertion data', () => {
      const testCase: TestCasePlan = {
        id: 'export-case-1',
        name: 'Standard export test',
        type: 'form',
        priority: 'p0',
        relatedPageIds: ['login-page', 'dashboard-page'],
        markdownPath: 'export/standard.md',
        preconditions: ['User is on login page'],
        steps: [
          {
            description: 'Fill the "username" field with "testuser"',
            expectedResult: 'Username is entered',
          },
          {
            description: 'Fill the "password" field with "password123"',
            expectedResult: 'Password is entered',
          },
          {
            description: 'Click the "Login" button',
            expectedResult: 'Form is submitted',
          },
          {
            description: 'Verify the page shows "Welcome"',
            expectedResult: 'Welcome message appears',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Verify no planner metadata in markdown
      expect(markdown).not.toContain('relatedPageIds')
      expect(markdown).not.toContain('login-page')
      expect(markdown).not.toContain('dashboard-page')
      expect(markdown).not.toContain('export-case-1')

      // Verify standard spec structure
      expect(markdown).toContain('## Preconditions')
      expect(markdown).toContain('## Steps')
      
      const parseResult = parseMarkdownSpec(markdown)
      expect(parseResult.ok).toBe(true)
    })

    it('should generate specs with clear action patterns for tool mapping', () => {
      const testCase: TestCasePlan = {
        id: 'export-case-2',
        name: 'Tool mapping test',
        type: 'functional',
        priority: 'p1',
        relatedPageIds: ['products'],
        markdownPath: 'export/tools.md',
        preconditions: ['App is accessible'],
        steps: [
          {
            description: 'Navigate to /products',
            expectedResult: 'Products page loads',
          },
          {
            description: 'Click the "Add to Cart" button',
            expectedResult: 'Item is added to cart',
          },
          {
            description: 'Select "Express Shipping" from the shipping dropdown',
            expectedResult: 'Shipping option is selected',
          },
          {
            description: 'Verify the page shows "1 item"',
            expectedResult: 'Cart count is correct',
          },
          {
            description: 'Assert that "Checkout" button is visible',
            expectedResult: 'Checkout button appears',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      // Verify step patterns that export pipeline can recognize
      const steps = parseResult.value.steps

      // Navigate pattern
      expect(steps[0].text.toLowerCase()).toContain('navigate')
      expect(steps[0].kind).toBe('action')

      // Click pattern
      expect(steps[1].text.toLowerCase()).toContain('click')
      expect(steps[1].kind).toBe('action')

      // Select pattern
      expect(steps[2].text.toLowerCase()).toContain('select')
      expect(steps[2].kind).toBe('action')

      // Assertion patterns
      expect(steps[3].kind).toBe('assertion')
      expect(steps[4].kind).toBe('assertion')
    })

    it('should preserve template variables for export pipeline', () => {
      const testCase: TestCasePlan = {
        id: 'export-case-3',
        name: 'Template variables in export',
        type: 'form',
        priority: 'p0',
        relatedPageIds: ['auth'],
        markdownPath: 'export/template-vars.md',
        preconditions: ['Environment variables are set'],
        steps: [
          {
            description: 'Navigate to {{BASE_URL}}/login',
            expectedResult: 'Login page loads',
          },
          {
            description: 'Fill username with {{USERNAME}}',
            expectedResult: 'Username is entered',
          },
          {
            description: 'Fill password with {{PASSWORD}}',
            expectedResult: 'Password is entered',
          },
          {
            description: 'Click submit',
            expectedResult: 'Login is submitted',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Verify template variables are preserved (needed for export)
      expect(markdown).toContain('{{BASE_URL}}')
      expect(markdown).toContain('{{USERNAME}}')
      expect(markdown).toContain('{{PASSWORD}}')

      // Verify parseability
      const parseResult = parseMarkdownSpec(markdown)
      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      // Verify variables are in step text
      // First step is the auto-inserted login include
      expect(parseResult.value.steps[0].text).toContain('include: login')
      // Then the original steps follow
      expect(parseResult.value.steps[1].text).toContain('{{BASE_URL}}')
      expect(parseResult.value.steps[2].text).toContain('{{USERNAME}}')
      expect(parseResult.value.steps[3].text).toContain('{{PASSWORD}}')
    })

    it('should generate specs that work with IR locator validation', () => {
      const testCase: TestCasePlan = {
        id: 'export-case-4',
        name: 'IR locator compatibility',
        type: 'form',
        priority: 'p0',
        relatedPageIds: ['form-page'],
        markdownPath: 'export/locators.md',
        preconditions: ['Form page is loaded'],
        steps: [
          {
            description: 'Fill the "email" field with "test@example.com"',
            expectedResult: 'Email is entered',
          },
          {
            description: 'Fill the "phone" field with "1234567890"',
            expectedResult: 'Phone is entered',
          },
          {
            description: 'Click the "Submit" button',
            expectedResult: 'Form is submitted',
          },
          {
            description: 'Verify the page shows "Success"',
            expectedResult: 'Success message appears',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      // Verify fill steps have clear target descriptions
      const fillSteps = parseResult.value.steps.filter(s => 
        s.text.toLowerCase().includes('fill')
      )
      expect(fillSteps.length).toBe(2)
      
      // Each fill step should have quoted field name
      fillSteps.forEach(step => {
        expect(step.text).toMatch(/"[^"]+"\s+field/)
      })

      // Click step should have quoted button text
      const clickStep = parseResult.value.steps.find(s => 
        s.text.toLowerCase().includes('click')
      )
      expect(clickStep?.text).toMatch(/"[^"]+"\s+button/)
    })

    it('should not include priority/tags metadata that could affect export', () => {
      const testCase: TestCasePlan = {
        id: 'export-case-5',
        name: 'Clean export without metadata',
        type: 'functional',
        priority: 'p0',
        relatedPageIds: ['page-1', 'page-2', 'page-3'],
        markdownPath: 'export/clean.md',
        preconditions: ['App is ready'],
        steps: [
          {
            description: 'Navigate to /test',
            expectedResult: 'Test page loads',
          },
          {
            description: 'Verify the page shows "Test"',
            expectedResult: 'Test text is visible',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Should contain metadata in header but not in steps
      expect(markdown).toContain('Type: functional')
      expect(markdown).toContain('Priority: P0')

      // Should NOT leak internal IDs or page references
      expect(markdown).not.toContain('export-case-5')
      expect(markdown).not.toContain('page-1')
      expect(markdown).not.toContain('page-2')
      expect(markdown).not.toContain('relatedPageIds')

      // Steps should be clean
      const stepsSection = markdown.split('## Steps')[1]
      expect(stepsSection).toBeDefined()
      expect(stepsSection).not.toContain('export-case-5')
      expect(stepsSection).not.toContain('page-1')
    })
  })

  describe('Planner metadata handling', () => {
    it('should keep test type and priority visible but not in IR-relevant sections', () => {
      const testCase: TestCasePlan = {
        id: 'meta-case-1',
        name: 'Metadata visibility test',
        type: 'security',
        priority: 'p0',
        relatedPageIds: ['admin'],
        markdownPath: 'meta/test.md',
        preconditions: ['Admin access is available'],
        steps: [
          {
            description: 'Navigate to /admin',
            expectedResult: 'Admin page loads',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Type and priority should be in header (useful for test organization)
      const headerSection = markdown.split('## Preconditions')[0]
      expect(headerSection).toContain('Type: security')
      expect(headerSection).toContain('Priority: P0')

      // But not in Preconditions or Steps sections
      const preconditionsSection = markdown.split('## Preconditions')[1]?.split('## Steps')[0]
      expect(preconditionsSection).not.toContain('Type:')
      expect(preconditionsSection).not.toContain('Priority:')

      const stepsSection = markdown.split('## Steps')[1]
      expect(stepsSection).not.toContain('Type:')
      expect(stepsSection).not.toContain('Priority:')
    })

    it('should not include TestPlan-specific fields in markdown', () => {
      const testCase: TestCasePlan = {
        id: 'meta-case-2',
        name: 'No TestPlan leakage',
        type: 'form',
        priority: 'p1',
        relatedPageIds: ['login', 'dashboard', 'profile'],
        markdownPath: 'meta/no-leak.md',
        preconditions: ['User is logged out'],
        steps: [
          {
            description: 'Navigate to /login',
            expectedResult: 'Login page appears',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)

      // Should NOT contain TestPlan internal fields
      expect(markdown).not.toContain('relatedPageIds')
      expect(markdown).not.toContain('markdownPath')
      expect(markdown).not.toContain('meta-case-2')
      expect(markdown).not.toContain('"id"')
      expect(markdown).not.toContain('"login"')
      expect(markdown).not.toContain('"dashboard"')
      expect(markdown).not.toContain('"profile"')
    })
  })

  describe('Export pipeline step patterns', () => {
    it('should generate navigate steps in recognizable format', () => {
      const testCase: TestCasePlan = {
        id: 'pattern-1',
        name: 'Navigate patterns',
        type: 'navigation',
        priority: 'p1',
        relatedPageIds: ['home'],
        markdownPath: 'patterns/navigate.md',
        preconditions: ['Browser is open'],
        steps: [
          {
            description: 'Navigate to /',
            expectedResult: 'Home page loads',
          },
          {
            description: 'Navigate to /about',
            expectedResult: 'About page loads',
          },
          {
            description: 'Navigate to {{BASE_URL}}/contact',
            expectedResult: 'Contact page loads',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      parseResult.value.steps.forEach(step => {
        expect(step.text.toLowerCase()).toContain('navigate')
        expect(step.kind).toBe('action')
      })
    })

    it('should generate fill steps in recognizable format', () => {
      const testCase: TestCasePlan = {
        id: 'pattern-2',
        name: 'Fill patterns',
        type: 'form',
        priority: 'p0',
        relatedPageIds: ['form'],
        markdownPath: 'patterns/fill.md',
        preconditions: ['Form is visible'],
        steps: [
          {
            description: 'Fill the "name" field with "John Doe"',
            expectedResult: 'Name is entered',
          },
          {
            description: 'Fill the "email" field with {{EMAIL}}',
            expectedResult: 'Email is entered',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      parseResult.value.steps.forEach(step => {
        expect(step.text.toLowerCase()).toContain('fill')
        expect(step.text).toMatch(/"[^"]+"\s+field/)
        expect(step.kind).toBe('action')
      })
    })

    it('should generate assertion steps in recognizable format', () => {
      const testCase: TestCasePlan = {
        id: 'pattern-3',
        name: 'Assertion patterns',
        type: 'functional',
        priority: 'p1',
        relatedPageIds: ['result'],
        markdownPath: 'patterns/assert.md',
        preconditions: ['Action completed'],
        steps: [
          {
            description: 'Verify the page shows "Success"',
            expectedResult: 'Success message is visible',
          },
          {
            description: 'Assert that "Continue" button is visible',
            expectedResult: 'Continue button appears',
          },
        ],
      }

      const markdown = buildMarkdownForTestCase(testCase)
      const parseResult = parseMarkdownSpec(markdown)

      expect(parseResult.ok).toBe(true)
      if (!parseResult.ok) return

      parseResult.value.steps.forEach(step => {
        expect(step.kind).toBe('assertion')
        expect(step.text.toLowerCase()).toMatch(/verify|assert/)
      })
    })
  })
})
